apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bigtech-chat-spring

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - user-service.yaml
  - friend-service.yaml
  - chat-service.yaml
  - api-gateway.yaml
  - hpa.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: bigtech-chat-spring-platform
